feat: components
Arrow-air/web-services-public pull request #4
Opened 2023-04-11 21:38 UTC by owlot

https://www.dmo.flyarrow.io/

2023-04-12 01:04 UTC, ServiceDog requested changes

2023-04-12 08:51 UTC, owlot commented on src/components/Slide/Conops.vue
> +                <a href="#" class="btn btn-secondary">Download the CONOPS</a>
We can skip the slide for now yeah. Don't know how far we are with the CONOPS.

2023-04-12 08:53 UTC, owlot commented on src/components/Slide/Infrastructure.vue
@miss-queenNL will go over this version and do the last design checks. I'll ensure this is also noted for her to make it clear it's draggable.

2023-04-12 08:58 UTC, owlot commented on src/content/discover.yaml
> +        Leave behind the constraints of traditional transportation methods and embrace increased speed and reliability in delivering critical care. Organ delivery, vaccines, blood packets, etc.
fixed: 496bb9f0c35b8a63239139904045c8e8762b8f37

2023-04-12 08:58 UTC, owlot commented on src/components/Slide/Conops.vue
> +                <a href="#" class="btn btn-secondary">Download the CONOPS</a>
Commented out in 496bb9f0c35b8a63239139904045c8e8762b8f37

2023-04-13 21:32 UTC, ServiceDog approved these changes

2023-04-13 21:32 UTC, merged